### ISSUE TITLE
açılmıyo

### ISSUE THREAD

**Issue by AlaattinK02** [omerayyildiz/Pardus-AutoSetup#2]
hata veriyo

**Comment by omerayyildiz** [comment]
Ne hatası veriyor acaba??

**Comment by AlaattinK02** [comment]
tıklayınca VSCode açılıyo

**Comment by omerayyildiz** [comment]
Gnome kullanıyorsan üstte bulunan üç noktaya tıklayıp komut dosyalarını çalıştır seçeneğini açıcaksın.
